apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: togglemaster
type: Opaque
stringData:
  REDIS_URL: "PLACEHOLDER_RUN_RENDER_SECRETS_SH"
  SERVICE_API_KEY: "PLACEHOLDER_RUN_RENDER_SECRETS_SH"
  AWS_SQS_URL: "PLACEHOLDER_RUN_RENDER_SECRETS_SH"
